language: rust
sudo: required
rust:
  - beta
  - stable
  - nightly
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
env:
  DBCONN=postgresql://postgres@127.0.0.1/testdb

install:
  - rustc --version

before_script:
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;" -U postgres testdb

script:
  - cargo build -v
  - cargo test -v
  - cargo test -- --ignored
